import type { Metadata } from 'next';
import { Inter, Poppins } from 'next/font/google';
import '@/app/globals.css';

const inter = Inter({ subsets: ['latin'] });
const poppins = Poppins({ weight: ['400', '600', '700'], subsets: ['latin'] });

export { inter, poppins };

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ja" className="min-h-screen">
            <body
                className={`${inter.className} flex flex-col bg-gray-50 text-gray-900 dark:bg-gray-900 dark:text-gray-100`}
            >
                <main className="flex-grow container mx-auto px-4 sm:px-6 lg:px-8 py-8">
                    {children}
                </main>
            </body>
        </html>
    );
}
